### Functions 

In [20]:
def helloWorldXY(x, y):
    if x < 10:
        print("hello world, x was < 10")
    elif x < 20:
        print("hello world, x is between 10 and 20")
    else:
        print("Hello world, x is > 20")
    return x + y

for i in range(8, 25, 5):
    print(f"Now running with i: {i}")
    r = helloWorldXY(i, i)
    print("The result from helloWorldXY is: {}".format(i, r))
              

Now running with i: 8
hello world, x was < 10
The result from helloWorldXY is: 8
Now running with i: 13
hello world, x is between 10 and 20
The result from helloWorldXY is: 13
Now running with i: 18
hello world, x is between 10 and 20
The result from helloWorldXY is: 18
Now running with i: 23
Hello world, x is > 20
The result from helloWorldXY is: 23


### Loops

In [21]:
for _ in range(3):
    print(_, end = "\t")
    
print()
for _ in [0, 1, 3, 7]:
    print(_, end  = "\t")

print()
i = 102
while i < 112:
    print(i, end = "\t")
    i += 1

0	1	2	
0	1	3	7	
102	103	104	105	106	107	108	109	110	111	

### Continue and break

In [24]:
while True:
    print("Enter a while loop")
    break

Enter a while loop


## Numpy and Lists

In [48]:
import numpy as np

# Appending an element
a = np.array(["Hello", "World"])
a = np.append(a, "!!!!")
print(a)
a = np.append(a, [1, "Hi ", "There"])

for _ in a:
    print(_)
    
for i, j in enumerate(a):
    print("Index: {} Value: {}".format(i, j))

['Hello' 'World' '!!!!']
Hello
World
!!!!
1
Hi 
There
Index: 0 Value: Hello
Index: 1 Value: World
Index: 2 Value: !!!!
Index: 3 Value: 1
Index: 4 Value: Hi 
Index: 5 Value: There


### Np functions

In [49]:
b = np.array([0, 100, 3, 6, 76, 90, 43])
print(f"The maximum is {np.max(b)}")
print(f"The average is {np.average(b)}")
print(f"The max index is {np.argmax(b)}")

The maximum is 100
The average is 45.42857142857143
The max index is 1


### Type

In [53]:
print("Datatype of a is {} and that of b is {}".format(type(a), type(b)))
print("Datatype of a[3] is {} and that of b[3] is {}".format(type(a[3]), type(b[3])))

Datatype of a is <class 'numpy.ndarray'> and that of b is <class 'numpy.ndarray'>
Datatype of a[3] is <class 'numpy.str_'> and that of b[3] is <class 'numpy.int64'>


In [55]:
print("Datatype of a is {} and that of b is {}".format(a.dtype, b.dtype))
print("Datatype of a[3] is {} and that of b[3] is {}".format(a.dtype, b[3].dtype))

Datatype of a is <U21 and that of b is int64
Datatype of a[3] is <U21 and that of b[3] is int64


### Random 

In [87]:
c = np.random.randint(-500,500, 6)
print(c)

[   4 -383  362   -8   54  -91]


In [75]:
d = np.random.random((6))
print(d)

[0.50649399 0.49104771 0.24283773 0.93815172 0.78589119 0.71535846]


In [81]:
e = np.random.random((2, 3))
print(e)

[[0.480692   0.85681576 0.59623064]
 [0.22740505 0.37871858 0.28474104]]


In [93]:
e.ravel() == e.flatten()

array([ True,  True,  True,  True,  True,  True])

In [85]:
e.flatten()

array([0.480692  , 0.85681576, 0.59623064, 0.22740505, 0.37871858,
       0.28474104])

In [90]:
all(e.ravel() == e.flatten())

True

In [91]:
(e.ravel() == e.flatten()).all()

True

In [96]:
c + e.flatten()

array([   4.480692  , -382.14318424,  362.59623064,   -7.77259495,
         54.37871858,  -90.71525896])

In [99]:
f = np.random.rand(2, 3)
print(f)

[[0.76876456 0.04052609 0.2288845 ]
 [0.79049673 0.09330056 0.4164229 ]]


In [103]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### Shape

In [107]:
f.shape

(2, 3)

In [108]:
c.shape

(6,)

In [116]:
g = np.zeros([4, 2, 3])
print(f"The shape of {g} is: {g.shape}")

The shape of [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] is: (4, 2, 3)


### Jupyter Specifics

In [119]:
!pip install numpy

In [121]:
!ls -l

total 435436
-rw-rw-r-- 1 login login  53843883 Sep 19 08:52  Going+Further+With+CNNs+Videos.zip
-rw-rw-r-- 1 login login  22214630 Sep 19 08:48  Introduction+to+CNNs+Videos.zip
drwxrwxr-x 2 login login      4096 Sep 21 14:34  Introduction+to+Machine+Learning+Videos
-rw-rw-r-- 1 login login  23547498 Sep 19 08:46  Introduction+to+Machine+Learning+Videos.zip
-rw-rw-r-- 1 login login   8734369 Sep 19 09:04  Introduction+to+TensorFlow+Lite+Videos.zip
-rw-rw-r-- 1 login login     13007 Sep 22 18:04 'Intro to python and collab.ipynb'
-rw-rw-r-- 1 login login  75028407 Sep 19 09:04  NLP_+Recurrent+Neural+Networks+Videos.zip
-rw-rw-r-- 1 login login  50042810 Sep 19 09:04  NLP_+Tokenization+and+Embeddings+Videos.zip
-rw-rw-r-- 1 login login  23865367 Sep 19 09:03  Saving+and+Loading+Models+Videos.zip
-rw-rw-r-- 1 login login 118112114 Sep 19 09:04  Time+Series+Forecasting+Videos.zip
-rw-rw-r-- 1 login login  25246508 Sep 19 08:52  Transfer+Learning+Videos.zip
drwxrwxr-x 2 login login      409

In [129]:
!pwd

/home/login/Documents/Intro to TF


In [132]:
!cd /
!ls -l

total 435436
-rw-rw-r-- 1 login login  53843883 Sep 19 08:52  Going+Further+With+CNNs+Videos.zip
-rw-rw-r-- 1 login login  22214630 Sep 19 08:48  Introduction+to+CNNs+Videos.zip
drwxrwxr-x 2 login login      4096 Sep 21 14:34  Introduction+to+Machine+Learning+Videos
-rw-rw-r-- 1 login login  23547498 Sep 19 08:46  Introduction+to+Machine+Learning+Videos.zip
-rw-rw-r-- 1 login login   8734369 Sep 19 09:04  Introduction+to+TensorFlow+Lite+Videos.zip
-rw-rw-r-- 1 login login     14314 Sep 22 18:52 'Intro to python and collab.ipynb'
-rw-rw-r-- 1 login login  75028407 Sep 19 09:04  NLP_+Recurrent+Neural+Networks+Videos.zip
-rw-rw-r-- 1 login login  50042810 Sep 19 09:04  NLP_+Tokenization+and+Embeddings+Videos.zip
-rw-rw-r-- 1 login login  23865367 Sep 19 09:03  Saving+and+Loading+Models+Videos.zip
-rw-rw-r-- 1 login login 118112114 Sep 19 09:04  Time+Series+Forecasting+Videos.zip
-rw-rw-r-- 1 login login  25246508 Sep 19 08:52  Transfer+Learning+Videos.zip
drwxrwxr-x 2 login login      409